version: 2
jobs:
  install-dependency:
    docker:
      - image: circleci/openjdk:17-jdk

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  lint:
    docker:
      - image: circleci/openjdk:17-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew ktlint
  test:
    docker:
      - image: circleci/openjdk:17-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew test

workflows:
  version: 2
  continuous-integration:
    jobs:
      - install-dependency
      - lint:
          requires:
            - install-dependency
      - test:
          requires:
            - install-dependency
